config/routes.rb
Rails.application.routes.draw do
  get 'employees/index'
  get 'employees/new'
  devise_for :users
  get 'home/index'
  get 'home/error'
  delete 'destroyclient' => 'clients#destroy'
  delete 'destroyinvoice' => 'invoices#destroy'


  root 'home#index'

  resources :clients
  resources :invoices
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	before_save { self.email = email.downcase }
	regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true, length: {maximum: 40}
	validates :email, presence: true, length: {maximum: 255}, format: { with: regex },uniqueness: { case_sensitive: false }

	has_many :invoices, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
	before_save { self.email = email.downcase }
	regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true
	validates :email, presence: true, length: { maximum: 255 }, format: { with: regex }, uniqueness: true
	validates :joining_date, presence: true
	validates :birth_date, presence: true
	has_one_attached :profile
	has_one_attached :a_front
	has_one_attached :a_back
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :client
  has_one_attached :document
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	def after_sign_in_path_for(resource) 
      current_user.admin == true ? clients_url : home_error_path
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	def index
		@client = Client.new
		@clients = Client.all
	end

	def new
		@client = Client.new
	end

	def create
		@client = Client.new(client_params)
		@clients = Client.all
		
    respond_to do |format|
      if @client.save
      	@clients = Client.all
        format.html { redirect_to clients_url, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
        format.js
      end
    end
	end

	def edit
    @client = Client.find(params[:id])
  end

  def update
  	@client = Client.find(params[:id])
    respond_to do |format|
      if @client.update(client_params)
        @clients = Client.all
        format.html { redirect_to clients_url, notice: "Client was successfully updated." }
        format.js
      else
        format.html { render :edit}
        format.js
      end
    end
  end

  def destroy
  	@client = Client.find_by(params[:id])
  	@client.destroy
  	respond_to do |format|
      format.html { redirect_to @client, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

	def show
		@client = Client.find(params[:id])
	end

	private
	def client_params
		params.require(:client).permit(:name, :email)
	end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employee = Employee.new
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params) 

    respond_to do |format|
      if @employee.save
        @employees = Employee.all
        format.html { redirect_to employees_url, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @employee }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employees.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def show
    @employee = Employee.find(params[:id])
    @employee = Employee.new
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    respond_to do |format|
      if @employee.update(employee_params)
        @employees = Employee.all
        format.html { redirect_to employees_url, notice: "Client was successfully updated." }
        format.js
      else
        format.html { render :edit}
        format.js
      end
    end
  end

  def destroy
    @employee = Employee.find_by(params[:id])
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to @employee, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  private
  def employee_params
    params.require(:employee).permit(:name, :email, :joining_date, :birth_date, :profile, :a_front, :a_back)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
	def index
		@invoices = Invoice.all
	end
	def new
		@invoice = Invoice.new
		@clients = Client.all
	end

	def create
		@invoice = Invoice.new(invoice_params)
   
		respond_to do |format|
      if @invoice.save
				@client = Client.find(@invoice.client_id)
		
      	@invoices = Invoice.all
        format.html { redirect_to invoice_url(@invoice.client_id), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
        format.js
      end
    end
	end

	def edit
    @invoice = Invoice.find(params[:id])
  	@client = Client.find(@invoice.client_id)
  end

  def update
  	@invoice = Invoice.find(params[:id])
  	@client = Client.find(@invoice.client_id)   
  	
    respond_to do |format|
      if @invoice.update(invoice_params)                                                                                                              
        @invoices = Invoice.all
        format.html { redirect_to invoices_url, notice: "Invoice was successfully updated." }
        format.js
      else
        format.html { render :edit}
        format.js
      end
    end
  end

  def destroy
  	@invoice = Invoice.find_by(params[:id])
  	@invoice.destroy
  	respond_to do |format|
      format.html { redirect_to @invoice, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

	def show
		@invoice = Invoice.new
		@invoices = Invoice.all
		@client = Client.find(params[:id])
    # @client_inv = @client.invoices
	end

	private
	def invoice_params
		params.require(:invoice).permit(:discount, :date, :amount, :client_id, :document)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
	def current_client
		 Client.find_by(params[:id])
	end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/clients/_clients_body.html.erb
<table class="clients" style="text-align:center;">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Edit</th>
    <th>Delete</th>
    <th>Show</th>
  </tr>

  <% @clients.each do |client| %>
  <tbody class="edit_body">
    <tr class="tr_<%= client.id %>">
      <td><%= client.name %></td>
      <td><%= client.email %></td>
      <!-- <td><%#= link_to 'Edit', edit_client_path(client), class:"nav-link" %></td> -->
     <!--  <td><%#= button_to 'Delete', destroyclient_path, method: :delete,class:"btn btn-danger" %></td> -->
      <td><button class="btn btn-primary edit" data-id="<%= client.id %>">Edit</button></td>
      <td><button class="btn btn-danger del" data-id="<%= client.id %>">Delete</button></td>
      <td><%= link_to 'Show', client_path(client), class:"nav-link" %></td>
    </tr>
  </tbody>
<% end %>
</table>

app/views/clients/_form.html.erb
<div class="row justify-content-center edit_form">
  <div class="col-md-4 col-md-offset-3 ">
  	<%= form_for(@client) do |f| %>
  	<%= render 'errors/error' %>
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %> <br>

      <%= f.label :email %>
      <%= f.email_field :email, class:"form-control" %> <br>

      <%#= f.submit "Client", class: "btn btn-success insert",type:"button" %>

      <% if @client.id.present? %>
        <button class="btn btn-danger update", data-id="<%= client.id%>", type="button">Update</button>
      <% else %>
        <%= f.submit "Client", class: "btn btn-success insert",type:"button" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/clients/create.js.erb
console.log("create.js");

$('table.clients').html("<%= escape_javascript(render('clients/clients_body')) %>");

app/views/clients/destroy.js.erb
console.log("delete client");

$('.tr_'+<%= @client.id %>).remove();

app/views/clients/edit.html.erb
<% provide(:title, "Edit client") %>
<h3 style="text-align: center;">Edit client</h3>

<%= render 'form', client: @client %>

app/views/clients/edit.js.erb
console.log("edit.js");

$('.edit_form').html("<%= escape_javascript(render 'form', client: @client) %>");

app/views/clients/index.html.erb
<h3 style="text-align: center;">Client details</h3>

<%= render 'form', client: @client %> <br>
<%= render 'clients/clients_body' %>

<script type="text/javascript">
		$(document).ready(function(){
		  $(document).on('click', '.del', function(event) {
		  	console.log('inside click-->',$(this).data('id'));
		    $.ajax({
		    	url: '/destroyclient',
		    	type: 'DELETE',
		    	dataType: 'script',
		    	data: {id: $(this).data('id')},
		    })
		    .done(function() {
		    	console.log("success");
		    })
		    .fail(function() {
		    	console.log("error");
		    })
		    .always(function() {
		    	console.log("complete");
		    });
		  });

		  $('.insert').click(function(event) {
		  	$.ajax({
		  		url: '/clients',
		  		type: 'POST',
		  		dataType: 'script',
		  		data :$('form').serialize(),
	 			beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
		  	})
		  	.done(function() {
		  		console.log("success");
		  	})
		  	.fail(function() {
		  		console.log("error");
		  	})
		  	.always(function() {
		  		console.log("complete");
		  	});
		  });

		  $('.edit').click(function(event) {
		  	console.log("edit");
		  	$.ajax({
		  		url: '/clients/' + $(this).data('id') + '/edit',
		  		type: 'GET',
		  		dataType: 'script'
		  	})
		  	.done(function() {
		  		console.log("success");
		  	})
		  	.fail(function() {
		  		console.log("error");
		  	})
		  	.always(function() {
		  		console.log("complete");
		  	});
		  });

		  $(document).on('click', '.update', function(event) {
		  	console.log('update');
		  	$.ajax({
		  		url: '/clients/' + $(this).data('id') + '/',
		  		type: 'PATCH',
		  		dataType: 'script',
		  		data :$('form').serialize(),
		  		beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
		  	})
		  	.done(function() {
		  		console.log("success");
		  	})
		  	.fail(function() {
		  		console.log("error");
		  	})
		  	.always(function() {
		  		console.log("complete");
		  	});
		  	
		  });
		});
</script>

app/views/clients/new.html.erb
<% provide(:title, "new client") %>
<h3 style="text-align: center;">Create new client</h3>

<%= render 'form', client: @client %>

app/views/clients/show.html.erb
<div class="row justify-content-center">
	<div class="card col-md-4">
	  <div class="card-header text-center" >
	    <h3><%= @client.name %></h3>
	  </div>
	  <div class="card-body text-center">
	    <p class="card-text"><%= @client.email %></p>
	    <%= link_to "Create Invoice", invoice_path, class: "btn btn-primary" %>
	  </div>
	</div>
</div>

app/views/clients/update.js.erb
console.log("udpate.js");

$('table.clients').replaceWith("<%= escape_javascript(render('clients/clients_body')) %>");

app/views/employees/_employees_body.html.erb
<tbody class="employee">
	<% @employees.each do |emp| %>
  	<tr class="tr_<%= emp.id %>">
  		<td><%= emp.name %></td>
  		<td><%= emp.email %></td>
  		<td><%= emp.joining_date %></td>
  		<td><%= emp.birth_date %></td>
      <td><%= image_tag(emp.profile, style:'width:60%') %></td>
      <td><%= image_tag(emp.a_front, style:'width:60%') %></td>
      <td><%= image_tag(emp.a_back, style:'width:60%') %></td>
  		<td>
          <button class="btn btn-dark edit" data-id="<%= emp.id %>"><i class="fas fa-edit"></i></button>
        </td>
  		<td>
          <button class="btn btn-dark del" data-id="<%= emp.id %>"><i class="fas fa-trash"></i></button>
        </td>
  	</tr>
	<% end %>
</tbody>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
	<div class="container-fluid">
	  <div class="row">
	    <div class="col">
	      <%= f.label :name, class:"d-flex justify-content-center" %>
      	<%= f.text_field :name, class:"form-control"  %>
	    </div>
	    <div class="col">
	      <%= f.label :email, class:"d-flex justify-content-center" %>
      	<%= f.email_field :email, class:"form-control"  %>
	    </div>
	    <div class="col">
	      <%= f.label :joining_date, class:"d-flex justify-content-center" %>
     		<%= f.datetime_field :joining_date, class:"form-control" %>
	    </div>
	    <div class="col">
	    	<%= f.label :birth_date,  class:"d-flex justify-content-center" %>
     		<%= f.datetime_field :birth_date, class:"form-control" %>
	    </div>
	    <div class="col">
	    	<%= f.label :profile,  class:"d-flex justify-content-center" %>
     		<%= f.file_field :profile, class:"form-control" %>
	    </div>
	    <div class="col">
	    	<%= f.label :a_front,  class:"d-flex justify-content-center" %>
     		<%= f.file_field :a_front, class:"form-control" %>
	    </div>
	    <div class="col">
	    	<%= f.label :a_back,  class:"d-flex justify-content-center" %>
     		<%= f.file_field :a_back, class:"form-control" %>
	    </div>
	    <div class="col">
	    	<% if @employee.id.present? %>
			    <button class="btn btn-primary update", data-id="<%= employee.id%>", type="button">Update</button>
			  <% else %>
			    <%= f.submit "create", class: "btn btn-danger insert", type:"button" %>
			  <% end %>
	    </div>
	  </div>
	</div>
<% end %>

app/views/employees/create.js.erb
console.log("create");

$('.employee').remove();
$('table.clients').append("<%= escape_javascript(render('employees/employees_body')) %>");

app/views/employees/destroy.js.erb
console.log("destroy");


$('.tr_'+<%= @employee.id %>).remove();

app/views/employees/edit.js.erb
console.log("edit");

$('form.new_employee').html("<%= escape_javascript(render 'form', employee: @employee) %>");

app/views/employees/index.html.erb
<% provide(:title, "employee") %>

<%= render 'form', employee: @employee %> <br>

<table class="clients" style="text-align:center;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Joining Date</th>
      <th>Birth Date</th>
      <th>Profile</th>
      <th>Adhar Front pick</th>
      <th>Adhar Back pick</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <%= render 'employees/employees_body' %>
</table>

<script type="text/javascript">
	$(document).ready(function(){
	  $(document).on('click', '.insert', function(event) {

      var formData = new FormData();
     
      formData.append('employee[name]',$('#employee_name').val())
      formData.append('employee[email]',$('#employee_email').val())
      formData.append('employee[joining_date]',$('#employee_joining_date').val())
      formData.append('employee[birth_date]',$('#employee_birth_date').val())
      formData.append('employee[profile]', $('#employee_profile')[0].files[0])
      formData.append('employee[a_front]', $('#employee_a_front')[0].files[0])
      formData.append('employee[a_back]', $('#employee_a_back')[0].files[0])
      // formData.append('invoice[client_id]', $('#invoice_client_id').val())

      $.ajax({
        url: '/employees',
        cache: false,
        contentType: false,
        processData: false,
        data: formData,
        enctype: 'multipart/form-data',
        type: 'POST',
        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
        success: function(response) {
            console.log(response);
        },
        error: function(error) {
            console.log(error);
        }
      });
    });

	  $('.del').click(function(event) {
	  	console.log('del-->',$(this).data('id'));
	  	$.ajax({
          url: '/employees/' + $(this).data('id'),
          type: 'DELETE',
          dataType: 'script',
          data: {id: $(this).data('id')},
        })                          
        .done(function() {
          console.log("success");                                                
        })
        .fail(function() {
          console.log("error");
        })
        .always(function() {
          console.log("complete");
       	});
	  });

	  $('.edit').click(function(event) {
	  	console.log('edit-->', $(this).data('id'));
	  	$.ajax({
          url: '/employees/' + $(this).data('id') + '/edit',
          type: 'GET',
          dataType: 'script',
          data :$('form').serialize(),
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
        })
        .done(function() {
          console.log("success");
        })
        .fail(function() {
          console.log("error");
        })
        .always(function() {
          console.log("complete");
        });
	  });

	  $(document).on('click', '.update', function(event) {
      console.log("update class -->", $(this).data('id'));

      $.ajax({
        url: '/employees/' + $(this).data('id') + '/',
        type: 'PATCH',
        dataType: 'script',
        data: $('form').serialize(),
      })
      .done(function() {
        console.log("success");
      })
      .fail(function() {
        console.log("error");
      })
      .always(function() {
        console.log("complete");
      });
    });
	});
</script>

app/views/employees/new.html.erb
<% provide(:title, 'Employee') %>
<h3 style="text-align:center;">New employee</h3>

<%= render 'form', employee: @employee %> <br>

app/views/employees/show.html.erb
<%= @employee.name %>, <%= @employee.email %>

app/views/employees/update.js.erb
console.log("update");

$('table.clients tbody').replaceWith("<%= escape_javascript(render('employees/employees_body')) %>");

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? && current_user.admin == true %>
          <li class="nav-item">
            <%= link_to 'clients', clients_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Invoices', invoices_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'createEmployees', employees_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'sign up', new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'sign in', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  .rails-default-error-page {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  .rails-default-error-page div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  .rails-default-error-page div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  .rails-default-error-page h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  .rails-default-error-page div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body class="rails-default-error-page">
  <!-- This file lives in public/404.html -->
  <div class="dialog">
    <div>
      <h1>Sorry!!! You are not Admin</h1>
      <p>Only admin have an access to see this panel.</p>
    </div>
  </div>
</body>
</html>

app/views/home/index.html.erb
<%= image_tag('https://wallpapercave.com/wp/wp9486379.jpg') %>

app/views/invoices/_form.html.erb
<%= form_for(@invoice,multipart: true, class: "invoice-form") do |f| %>
  <%= f.label :discount %>
  <%= f.number_field :discount, class:"form-control" %> <br>

  <%= f.label :date %>
  <%= f.datetime_field :date, class:"form-control" %> <br>

  <%= f.label :amount %>
  <%= f.number_field :amount, class:"form-control" %> <br>

  <%= f.label :document %>
  <%= f.file_field :document, class:"form-control document", accept: ".pdf" %> <br>

  <%= f.number_field :client_id, class:"form-control",value: @client.id, type: :hidden %> <br>

  <% if @invoice.id.present? %>
    <button class="btn btn-secondary update", data-id="<%= invoice.id%>", type="button">Update</button>
  <% else %>
    <%= f.submit "create Invoice", class: "btn btn-success insert", type:"button" %>
  <% end %>
<% end %>

app/views/invoices/_invoices_body.html.erb
<tbody class="invoices">
  <% @invoices.each do |invoice| %>
    <% puts "#{invoice.client_id}===>#{@client.id}"  %>

    <% if invoice.client_id == @client.id %>
      <tr class="tr_<%= invoice.id %>">
        <td><%= invoice.discount %> %</td>
        <td><%= invoice.date %></td>
        <td><%= invoice.amount %> ₹ </td>
        <td><%= invoice.client_id %></td>
       <!--  <td><%#= link_to 'Edit', edit_invoice_path(invoice), class:"nav-link" %></td>  -->
        <td>
          <button class="edit btn btn-primary" data-id="<%= invoice.id %>">Edit</button>
        </td>
        <td>
          <button class="btn btn-danger del" data-id="<%= invoice.id %>">Delete</button>
        </td>
        <td><%= link_to 'Download', invoice.document,class:"nav-link", download: '' %></td>
        <td>
          <iframe src="<%= rails_blob_path(invoice.document, disposition: :inline) %>" height="100" width="100"></iframe>
        </td>
      </tr>
    <% end %>
  <% end %>
</tbody>

app/views/invoices/create.js.erb
console.log("create.js.erb");
// $('.invoices').remove();
$('table.clients').append("<%= escape_javascript(render('invoices/invoices_body')) %>");

app/views/invoices/destroy.js.erb
console.log("destroy");

$('.tr_'+<%= @invoice.id %>).remove();

app/views/invoices/edit.html.erb
<h3 style="text-align:center;">Edit invoice detail</h3>
<%= render 'form', invoice: @invoice %>

app/views/invoices/edit.js.erb
console.log("edit.js");

$('form.new_invoice').html("<%= escape_javascript(render 'form', invoice: @invoice) %>");

app/views/invoices/index.html.erb
<table class="clients" style="text-align:center;">
	<tr>
		<th>Discount</th>
		<th>Date</th>
		<th>Amount</th>
		<th>Client_id</th>
		<th>PDF</th>
		<th>show pdf</th>
	</tr>

	<% @invoices.each do |invoice| %>
  <tbody>
    <tr>
      <td><%= invoice.discount %></td>
      <td><%= invoice.date %></td>
      <td><%= invoice.amount %></td>
      <td><%= invoice.client_id %></td>
      <td><%= link_to 'Download', invoice.document,class:"nav-link", download: '' %></td>
      <td>
        <iframe src="<%= rails_blob_path(invoice.document, disposition: :inline) %>" height="100" width="100"></iframe>
      </td>
    </tr>
  </tbody>
<% end %>
</table>

app/views/invoices/new.html.erb
<h3 style="text-align:center;">Create new invoice</h3>

<%= render 'form', invoice: @invoice %> <br>

<div class="row justify-content-center">
  <div class="col-md-4 col-md-offset-3">
  	<%= form_for(@invoice) do |f| %>
      <%= f.label :discount %>
      <%= f.number_field :discount, class:"form-control" %> <br>

      <%= f.label :date %>
      <%= f.datetime_field :date, class:"form-control" %> <br>

      <%= f.label :amount %>
      <%= f.number_field :amount, class:"form-control" %> <br>

      <%= f.label :client %>
      <%= f.number_field :client_id, class:"form-control" %> <br>

      <%= current_client.id %>

      <%= f.submit "Client", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/invoices/update.js.erb
console.log("update.js");

$('table.clients tbody' ).replaceWith("<%= escape_javascript(render('invoices/invoices_body')) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
  </head>

  <body>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= render 'home/header' %> 
   
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>